maintainer        "MapR - Brad Anderson"
maintainer_email  "banderson@maprtech.com"
license           "Apache v2.0"
description       "Configures system users"
version           "0.1"
long_description  "Configures users"
